--- #YAML:1.0
name:               App-AutoBuild
version:            0.01
abstract:           A perl tool to make it quick and easy to compile a C project with automatic compilation of dependencies
author:
    - Joel Jensen <yobert@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
