--- #YAML:1.0
name:               App-AutoBuild
version:            0.04
abstract:           A perl tool to make it quick and easy to compile a C/C++ project with automatic compilation of dependencies
author:
    - Joel Jensen <yobert@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    autodie:              0
    IPC::System::Simple:  0
    perl:                 5.010000
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
